// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPm5uyW8uQsHVpZEIFky3Fh9K25PalmnI',
    appId: '1:163773573735:web:2c747fcbab6e6b8c89c2c2',
    messagingSenderId: '163773573735',
    projectId: 'library-8c0fe',
    authDomain: 'library-8c0fe.firebaseapp.com',
    storageBucket: 'library-8c0fe.firebasestorage.app',
    measurementId: 'G-46W112Y3JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtd39sKe6pFXYgTOF0cHD9njUbYIJqVIU',
    appId: '1:163773573735:android:e5caa8e41cef049b89c2c2',
    messagingSenderId: '163773573735',
    projectId: 'library-8c0fe',
    storageBucket: 'library-8c0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJE4Ec0n-GDjFmTc837guqXA9H1DZpZc',
    appId: '1:163773573735:ios:289cf7052e246c2b89c2c2',
    messagingSenderId: '163773573735',
    projectId: 'library-8c0fe',
    storageBucket: 'library-8c0fe.firebasestorage.app',
    iosClientId: '163773573735-g4l4r34aaj51tbuh7ibb543nlj9errc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJE4Ec0n-GDjFmTc837guqXA9H1DZpZc',
    appId: '1:163773573735:ios:289cf7052e246c2b89c2c2',
    messagingSenderId: '163773573735',
    projectId: 'library-8c0fe',
    storageBucket: 'library-8c0fe.firebasestorage.app',
    iosClientId: '163773573735-g4l4r34aaj51tbuh7ibb543nlj9errc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPm5uyW8uQsHVpZEIFky3Fh9K25PalmnI',
    appId: '1:163773573735:web:6676879048b7d95589c2c2',
    messagingSenderId: '163773573735',
    projectId: 'library-8c0fe',
    authDomain: 'library-8c0fe.firebaseapp.com',
    storageBucket: 'library-8c0fe.firebasestorage.app',
    measurementId: 'G-G444V3LHEC',
  );
}
